name = "TimeTracking ğŸ•°ï¸"
description = "Track and analyze your project-/work-times easialy across multiple devices  with this webxdc app."

version = 1
source_code_url = "https://github.com/webxdc/timetracking-webxdc"
